# Generated by Django 4.2.3 on 2023-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlankProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('blank_answer', models.CharField(help_text='Comma separated answers if there are multiple', max_length=255)),
            ],
        ),
    ]
